### PR TITLE
Add tests/test_primes.py, rand_prime() to primality/primality.py, fix naming

### LINKED ISSUE #15: Add new feature "rand_prime(m,n)", extending the "between(m,n)" function
## Summary
rand_prime(m,n): Returns a random prime number within the range m,n.
## Expected Result

It would be great to have a feature that returns a random prime number between the range as we already have "between(m,n)" that returns all the prime numbers between the range m,n.

## Reproduction Steps

```python
from primality import primality
print(primality.rand_prime(2,50))
17
print(primality.rand_prime(2,50))
29
```

## System Information
Python 3.8.6
macOS Catalina 10.15.7

### PR DESCRIPTION
**Pull request by tatanpoker09**
Hello there. I added a method which returns a random prime between two numbers. If no random prime is found, the method returns -1.

I also added unit tests for every method.

### CODE REVIEW

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @tatanpoker09 ! 

I just reviewed the request, it looks good!

There seem to be two minor issues on ``primality/primality.py``.

I suggest the following changes:

* Fix documentation string typo.
* TypeError() should refer to current function.
  
**📋 Final changes should look as follows:**

**primality/primality.py**

```python
    """
    Returns:
        integer -- A random prime number between m and n.
    """
```

```python

    if not isinstance(m, int):
        raise TypeError("rand_prime() expect parameter m to be int. Given: "
                        + str(type(m)) + '.')
    if not isinstance(n, int):
        raise TypeError("rand_prime() expect parameter n to be int. Given: "
                        + str(type(n)) + '.')
```

Due to your second contribution, you can just add it as a fix to #17 or apply the changes to both (#16, #17).
 
**Thank you!**

**Review by nbcl — CHANGES_REQUESTED** [review]
Fix documentation string typo.

**Review by nbcl — CHANGES_REQUESTED** [review]
TypeError() should refer to current function.

**Comment by tatanpoker09** [comment]
Hello there! Thanks for your response, I truly appreciate it 🎉
I just commited the requested changes:
- **Fix documentation string typo:** primality.py:191
- **TypeError() should refer to current function:** primality.py:195, primality.py:198

Greatly appreciate your review! Will be looking forward for your response.

EDIT: I forgot to mention, I added the fix to both pull requests, that should save you some time when reviewing.

**Comment by nbcl** [comment]
Apparently you have joined #17 with #16 in `Merge pull request #1 from tatanpoker09/fix/pep8`, so this request will also consider your proposed naming changes!

**Review by nbcl — COMMENTED** [review]
**Fixed:** Fix documentation string typo.

**Review by nbcl — COMMENTED** [review]
**Fixed:** TypeError() should refer to current function.

**Review by nbcl — APPROVED** [review]
Approved! ✔️

**Pull request merged**
