### PR TITLE
Adding nextprime()

### LINKED ISSUE #7: adding methods "nextprime(n)" and "prevprime(n)"
## Summary

Hi! I have an idea for two new functions that can be added. both accepts an int n.
1. nextprime(n) - returns the next greater prime than n
2. prevprime(n) - returns the previous prime number smaller than n.

## Example

```python
from primality import primality
print(primality.nextprime(3))
5
print(primality.prevprime(7))
5
print(primality.nextprime(-100))
2
```

I would like to start working on those two functions. is it OK?

### PR DESCRIPTION
**Pull request by yonatanGal**
Adding the function nextprime() to primality.py, updating README, adding NEXTPRIME.md to docs

### CODE REVIEW

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @yonatanGal! 

I just reviewed the request, it looks good!

I would suggest minor syntax fixes on lines ``145-149`` in ``primality/primality.py``.

* Rename ``temp`` to ``number`` to follow ``between()`` and ``prange()`` variable names.
* Change the ``while`` loop condition from ``1`` into ``True`` to follow ``between()`` and ``prange()`` variable names.
* Minor syntax fixes on ``number`` variable definition.

**📋 Final changes should look as follows:**

Lines ``145-149`` in ``primality/primality.py``

```python
number = n + 1 if n % 2 == 0 else n + 2
while True:
    if isprime(number):
        return number
    number += 2
```

**Thank you!**

**Comment by nbcl** [comment]
**⚠️ Important attribution information**

Please note that the current pull request is assigning the changes to the name ``jhonygal18`` but not to any GitHub user, you can check this out in the [last commit](9/commits). 

This means that if the pull request is merged, @yonatanGal (or the user ``jhonygal18``) will not be considered as authors of the changes.

To fix this problem, you should set your current ``user.name`` and the corresponding ``user.email`` (the email associated with @yonatanGal in GitHub) in Git Bash. 

```bash
$ git config user.name "Example Name"
$ git config --global user.email "email@example.com"
```

Finally, you should make a copy of your changes locally, make a new fork of the repository and add once again your changes to the fork. This will remove the last commit and set the user (@yonatanGal) as the only author of the commit.

After that is done, opening a new pull request should label @yonatanGal as the only author of the changes!

**Review by nbcl — COMMENTED** [review]
Rename ``temp`` to ``number`` to follow ``between()`` and ``prange()`` variable names.

**Review by nbcl — COMMENTED** [review]
Change the ``while`` loop condition from ``1`` into ``True`` to follow ``between()`` and ``prange()`` variable names.

**Review by nbcl — COMMENTED** [review]
Minor syntax fixes on ``number`` variable definition.

**Comment by yonatanGal** [comment]
Thank you for all your comments and help! I've sent another pull request, this time with the right user, and fixed the issues with the code.

**Comment by nbcl** [comment]
This request has been moved to #10.

**Pull request closed without merging**
