### PR TITLE
Add Python version check

### PR DESCRIPTION
**Pull request by TheFuzzyTech**
Apologies for the previous PR. It was messy!

### CODE REVIEW

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @thefuzzyjew! 

Don't worry, this things happen!

I just reviewed the new request and there seems to be a minor issue on ``primality/__init__.py``.

* ``os`` is being imported but not used (I think you meant to import ``sys``).
* The version variable ``py_ver`` is missing (The definition seems to be missing from the last request).

**📋 Final changes should look as follows:**

Following your variables from [#2](2), I suggest the following, as I assume they where your intended changes:

**primality/__init__.py**
```python
import sys

py_ver = sys.version_info
if py_ver.minor < 8 or py_ver.major < 3:
    msg = """
    Primality requires Python >= 3.8 to run
    .
    .
```

There aren't any parallelism issues anymore, so I will suggest those changes as code review, keeping the request open, and wait for your fixes!

**Thank you!**

**Review by nbcl — CHANGES_REQUESTED** [review]
``os`` is being imported but not used.

**Review by nbcl — CHANGES_REQUESTED** [review]
``py_ver`` variable is not defined.

**Comment by TheFuzzyTech** [comment]
This should be fixed in 4257edc24edb1fac0cf5c87172e727250d3f465a

**Review by nbcl — COMMENTED** [review]
**Fixed:** ``os`` is being imported but not used.

**Review by nbcl — COMMENTED** [review]
**Fixed:** ``py_ver`` variable is not defined.

**Review by nbcl — APPROVED** [review]
Approved! ✔️

**Pull request merged**
