### PR TITLE
Add between() to primality/primality.py

### LINKED ISSUE #5: Add new method to return all primes within a range(m,n) - Enhancement
Summary.

## Expected Result

I am planing to implement this function using Sieve of Eratosthenes.

## Reproduction Steps

```python
from primality import primality

primality.list_all_primes_within_range(5,10)
>> [5,7]
```

### PR DESCRIPTION
**Pull request by loge1998**

### CODE REVIEW

**Comment by loge1998** [comment]
Pls add your repo to hacktoberfest...

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @loge1998! 

I just reviewed the request, it looks good!

There seem to be minor optimality and syntax issues on ``primality/primality.py``.

I suggest the following changes:

* Function name should be smaller, to favour maximum line length guidelines. I suggest ``primality.between()``.
* First and last integers in range should be allowed to be negative.
* To favour optimality, lines ``121-126`` should be implemented as it's done in ``prange()``, this is: using a while loop. 
    - I suggest moving the first parameter to the following odd number (unless said input is 2), and then looping every 2 integers on every iteration, checking half the numbers (only odd) and avoiding doing ``i % 2 != 0``.  
    - Please check out lines ``61-67`` of ``primality/primality.py`` to understand this implementation. 
  
**📋 Final changes should look as follows:**

``primality.list_all_primes_within_range()`` -> ``primality.between()``

```python
primality.between(-100, 10)
>>> [2, 3, 5, 7]

primality.between(-100, -1)
>>> []

primality.between(2, 3)
>>> [2, 3]

primality.between(2, 2)
>>> [2]

primality.between(10, 0)
>>> []

primality.between(10, -10)
>>> []
```

**Thank you!**

**Comment by nbcl** [comment]
**🎉 Regarding Hacktoberfest**
> Pls add your repo to hacktoberfest

My understanding is that repository maintainers are not to be demanded to register to the event.

Check out their [FAQ](https://hacktoberfest.digitalocean.com/faq/)!

> **Can I make pull requests to issues/repositories that are not listed on the homepage?**
> Yes! Any public GitHub repository is good for Hacktoberfest.

**Good luck!**

**Review by nbcl — COMMENTED** [review]
Function name should be smaller, to favour maximum line length guidelines. I suggest ``primality.between()``.

**Review by nbcl — COMMENTED** [review]
First and last integers in range should be allowed to be negative.

**Review by nbcl — COMMENTED** [review]
Lines ``121-126`` should be implemented as it's done in ``prange()``.

**Comment by loge1998** [comment]
@nbcl pls check this one https://hacktoberfest.digitalocean.com/hacktoberfest-update.. They have changed the policy.. can you pls add the topic hacktoberfest to description

**Comment by loge1998** [comment]
Also i am working on the changes that you mentioned

**Comment by loge1998** [comment]
> **🎉 Thanks for your interest in contributing to Primality**
> 
> Hello @loge1998!
> 
> I just reviewed the request, it looks good!
> 
> There seem to be minor optimality and syntax issues on `primality/primality.py`.
> 
> I suggest the following changes:
> 
> * Function name should be smaller, to favour maximum line length guidelines. I suggest `primality.between()`.
> * First and last integers in range should be allowed to be negative.
> * To favour optimality, lines `121-126` should be implemented as it's done in `prange()`, this is: using a while loop.
>   
>   * I suggest moving the first parameter to the following odd number (unless said input is 2), and then looping every 2 integers on every iteration, checking half the numbers (only odd) and avoiding doing `i % 2 != 0`.
>   * Please check out lines `61-67` of `primality/primality.py` to understand this implementation.
> 
> **📋 Final changes should look as follows:**
> 
> `primality.list_all_primes_within_range()` -> `primality.between()`
> 
> ```python
> primality.between(-100, 10)
> >>> [2, 3, 5, 7]
> 
> primality.between(-100, -1)
> >>> []
> 
> primality.between(2, 3)
> >>> [2, 3]
> 
> primality.between(2, 2)
> >>> [2]
> 
> primality.between(10, 0)
> >>> []
> 
> primality.between(10, -10)
> >>> []
> ```
> 
> **Thank you!**

Negative number cant be prime.. So How will that make a difference?

**Comment by nbcl** [comment]
> @nbcl pls check this one https://hacktoberfest.digitalocean.com/hacktoberfest-update.. They have changed the policy.. can you pls add the topic hacktoberfest to description

I'm sorry. Currently I will not be performing this change to the repository.

**Comment by nbcl** [comment]
> Negative number cant be prime.. So How will that make a difference?

This was suggested to follow the same parameter rules as `range()`, which accepts negative integers.

**Comment by loge1998** [comment]
@nbcl Done with new changes.. Pls check and merge it

**Review by nbcl — COMMENTED** [review]
**Fixed:** Function name should be smaller.

**Review by nbcl — COMMENTED** [review]
**Fixed:** First and last integers in range should be allowed to be negative.

**Review by nbcl — COMMENTED** [review]
**Fixed:** Optimality issues.

**Review by nbcl — APPROVED** [review]
Approved! ✔️

**Pull request merged**
